---
title: "data queries Liverpool"
format: html
---

## Data access to Microsoft sql database

This code is useable for the sql-uks-dme-01 database This is restricted to 12F which is ?

```{r}
#| label: library
#| echo: false
#| message: false
#| warning: false

library(DBI)
library(odbc)

```

```{r}

con <- dbConnect(odbc(), driver = "ODBC Driver 17 for SQL Server", 
                      server = "sql-uks-dme-01.database.windows.net", 
                      database = "sql-nw-dme-01",
                      UID = "David.O-hagan@acp.ardengemcsu.nhs.uk",
                      Authentication = "ActiveDirectoryInteractive", timeout = 10)

#dbDisconnect(con)
```

```{sql connection=con, output.var="M1_results"}
#| label: sql number1
#| echo: false

--this  code builds a master patient index 
-- there are 3 million entries !!
-- The code is adapted from Roberta Piroddi MPI 01



SELECT Pseudo_NHS_Number
,MAX(case when left(GPPracticeCode,1)='V' then '0' else left(GPPracticeCode,6) end) 
	,P.X_CCG_OF_REGISTRATION
    ,P.X_CCG_OF_RESIDENCE
	,Dob
	,cast(datediff(d,cast(Dob+'-15' AS date),getdate())/365.25 AS int)
	,Sex
	--,EthnicGroup
	--,EthnicSubGroup
	--,InterpreterRequired
	,PL.Deceased
	,LSOA_Code
        ,0
	,''
	,''
	,LAT
	,LONG
  ,max(FrailtyScore) as FrailtyScore
	,'' as FrailtyLevel
--	,sum(total_household_population)
	--,living_alone_flag
	--,living_with_under_18_flag
	--,case when U.Der_Pseudo_NHS_Number is NULL then 'N' else 'Y' end AS UPRNMatch

FROM [Client_BTP].[vw_Cipha_SharedCare_Patient] AS P
LEFT JOIN 
	[Client_BTP].[vw_Cipha_SharedCare_Patient_Link] AS PL
	on P.FK_Patient_Link_ID = PL.PK_Patient_Link_ID
--LEFT JOIN 
--	[Client_SystemP_RW].[JWRefEthnicLookUp] AS E
-- LEFT OUTER JOIN 
--	[Client_SystemP].[PDS_UPRN_Indicators] AS U
--	on P.Pseudo_NHS_Number=U.Der_Pseudo_NHS_Number
WHERE 
	FK_Reference_Tenancy_ID = 2                  -- GP data
	and P.Deleted = 'N'                            -- Current data
	--and PL.Deceased <> 'Y'                         -- Not marked as deceased
	and Pseudo_NHS_Number is not NULL	
	and X_CCG_OF_REGISTRATION = '12F'
	
GROUP BY 
	Pseudo_NHS_Number
	,Dob
	,cast(datediff(d,cast(Dob+'-15' AS date),getdate())/365.25 AS int)
	,P.X_CCG_OF_REGISTRATION
  ,P.X_CCG_OF_RESIDENCE
	,Sex
	--,EthnicGroup
	--,EthnicSubGroup
	--,InterpreterRequired
	,Deceased
	,LSOA_Code
	,LAT
	,LONG
   --     ,living_alone_flag
	--,living_with_under_18_flag
	--,case when U.Der_Pseudo_NHS_Number is NULL then 'N' else 'Y' end



```

```{r}

head(M1_results)
#View(M1_results)
```

```{sql connection=con, output.var="M2_results"}
-- This is Roberta's step 2 
-- there is supposed to be a table constructed in sql but no write access
-- The results are a list of encounters/ events
-- 28 million rows !! so ? 2 hours

select P.Pseudo_NHS_Number
	,case when ENEV.Date is null then '1754-09-12' else cast(ENEV.Date as date) end
	,S.ConceptID
	--,REF.GroupName
	,max(ENEV.Value)
	,Type
	
	
from [Client_BTP].[vw_Cipha_SharedCare_Patient] as P
left join 
		(select FK_Patient_ID, FK_Reference_SnomedCT_ID, EventDate as Date, Value, 'EV' as Type
		from [Client_BTP].[vw_Cipha_SharedCare_GP_Events]
			union all
		select FK_Patient_ID, FK_Reference_SnomedCT_ID, EncounterDate as Date, '0' as Value, 'EN' as Type
		from [Client_BTP].[vw_Cipha_SharedCare_GP_Encounters]
		) as ENEV

	on P.PK_Patient_ID = ENEV.FK_Patient_ID

left join [Client_BTP].[vw_Cipha_SharedCare_Reference_SnomedCT] as S
	on S.PK_Reference_SnomedCT_ID = ENEV.FK_Reference_SnomedCT_ID

--left join [Client_BTP].[vw_Cipha_SharedCare_Reference_Coding] as REF    --- updated the group codes here
	--on S.ConceptID = REF.ConceptCode

where P.FK_Reference_Tenancy_ID = 2
	and Pseudo_NHS_Number is not null
	--and ConceptCode is not null
	and Date>'2014-04-01'
	and  X_CCG_OF_REGISTRATION = '12F'
	
group by P.Pseudo_NHS_Number 
	,case when ENEV.Date is null then '1754-09-12' else cast(ENEV.Date as date) end
	,S.ConceptID
	--,REF.GroupName
	,Type
limit 10 
```

```{sql}
--code for count egfr <60

--select distinct count(FK_Patient_ID) 
--from [Client_BTP].[vw_Cipha_SharedCare_GP_Events]
--where SuppliedCode = '80274001' -- GFR
--and Value < '60'  -- <60 = CKD3

--48731 entries 
```
